version = 0.1

[default.deploy.parameters]
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true

[staging.deploy.parameters]
stack_name = "toolshare-staging"
parameter_overrides = "Stage=staging"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true

[prod.deploy.parameters]
stack_name = "toolshare-prod"
parameter_overrides = "Stage=prod"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
